baseurl = "https://adamhollister.com" # Hostname (and path) to the root.
title = "Adam Hollister" # Site title.
theme = "adamhollister" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "dracula" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

# disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Adam Hollister" # Author's name.
    keywords = "blog,developer,personal" # Site keywords.

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # RTL support
    rtl = false

    #avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.
    #info = "Front" # Author's job title or info.
    #description = "John Doe's personal website" # Site description.
    #footercontent = "Enter a text here." # Add footer content
    # Custom CSS
    custom_css = ["css/custom-css.css"]
    # Multilanguage mode
    # langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/ahollister/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/adam_hollister/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/adamhollister/"

# Menu links
# [[menu.main]]
#     name = "Blog"
#     weight = 1
#     url  = "/blog/"
